name = "todo-pages"
compatibility_date = "2025-11-27"
account_id = "376877849ff0d4169066a70a423cc425"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "9b7dfe0a-dad5-48b1-aaf4-1536654b8b72"
