name = "todo-pages"
compatibility_date = "2025-11-27"
account_id = "376877849ff0d4169066a70a423cc425"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "926ebb06-096f-4174-aaa4-380cac5957ab"
