name = "todo-pages"
compatibility_date = "2025-11-27"
account_id = "376877849ff0d4169066a70a423cc425"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "ea07ae4b-14c9-4d6f-9897-d6acd74ba4d8"
