# Cloudflare Pages configuration (correct format)

name = "todo-pages"
compatibility_date = "2025-11-27"

pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "193d518a-91dd-4db3-a797-3447aa90b69c"
